services:
  api:
    container_name: agent-api
    build:
      context: ./agent-api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./agent-api/.env
    networks:
      - agent-network
  ui:
    container_name: agent-ui
    build:
      context: ./agent-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./agent-ui:/app
      - /app/node_modules
    depends_on:
      - api
    networks:
      - agents-network


volumes:
  data: 
  config:

networks:
  agent-network:
    name: agent-network
  

